<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Lenovo-PC" ignored="0" name="perfectMatch" tests="36" failures="9" timestamp="2021-04-14T20:13:13 IST" time="60.709" errors="0">
  <testcase name="BankFee" time="14.779" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- BankFee -->
  <testcase name="BankFee" time="1.303" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- BankFee -->
  <testcase name="BankFee" time="1.27" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- BankFee -->
  <testcase name="BankFee" time="1.304" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.BankFee(InboundTesting.java:54)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- BankFee -->
  <testcase name="Discount" time="1.278" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- Discount -->
  <testcase name="Discount" time="1.255" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- Discount -->
  <testcase name="Discount" time="1.256" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- Discount -->
  <testcase name="Discount" time="1.27" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.Discount(InboundTesting.java:71)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- Discount -->
  <testcase name="DuplicatePayment" time="1.282" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- DuplicatePayment -->
  <testcase name="DuplicatePayment" time="1.22" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- DuplicatePayment -->
  <testcase name="DuplicatePayment" time="1.291" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- DuplicatePayment -->
  <testcase name="DuplicatePayment" time="1.249" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.DuplicatePayment(InboundTesting.java:88)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- DuplicatePayment -->
  <testcase name="OnAccount" time="1.231" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- OnAccount -->
  <testcase name="OnAccount" time="1.252" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- OnAccount -->
  <testcase name="OnAccount" time="1.244" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- OnAccount -->
  <testcase name="OnAccount" time="1.264" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.OnAccount(InboundTesting.java:105)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- OnAccount -->
  <testcase name="OverPayment" time="1.226" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- OverPayment -->
  <testcase name="OverPayment" time="1.283" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- OverPayment -->
  <testcase name="OverPayment" time="2.566" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- OverPayment -->
  <testcase name="OverPayment" time="1.272" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.OverPayment(InboundTesting.java:122)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- OverPayment -->
  <testcase name="PerfectMatch" time="1.219" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- PerfectMatch -->
  <testcase name="PerfectMatch" time="1.39" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- PerfectMatch -->
  <testcase name="PerfectMatch" time="1.234" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- PerfectMatch -->
  <testcase name="PerfectMatch" time="1.333" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.PerfectMatch(InboundTesting.java:37)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- PerfectMatch -->
  <testcase name="ShortPayment" time="1.399" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- ShortPayment -->
  <testcase name="ShortPayment" time="1.215" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- ShortPayment -->
  <testcase name="ShortPayment" time="1.258" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- ShortPayment -->
  <testcase name="ShortPayment" time="1.196" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.ShortPayment(InboundTesting.java:139)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- ShortPayment -->
  <testcase name="Sundry" time="1.22" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- Sundry -->
  <testcase name="Sundry" time="1.207" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- Sundry -->
  <testcase name="Sundry" time="1.195" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- Sundry -->
  <testcase name="Sundry" time="1.213" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.Sundry(InboundTesting.java:156)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- Sundry -->
  <testcase name="WriteOff" time="1.696" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- WriteOff -->
  <testcase name="WriteOff" time="1.198" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- WriteOff -->
  <testcase name="WriteOff" time="1.228" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- WriteOff -->
  <testcase name="WriteOff" time="1.196" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.WriteOff(InboundTesting.java:173)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- WriteOff -->
</testsuite> <!-- perfectMatch -->
